### ISSUE TITLE
Описание базового функционала

### ISSUE THREAD

**Issue by iphilka** [Bards-Service/bardsExpress#5]
Описание страниц интерфейса + схемы
Описание функционала бэкенда согласно интерфейса.

**Comment by AndrewNikitin127** [comment]
Главная страница.

Страница барда с заказом песен: 

Ручка получения информации о барде по ссылке. 

Список песен и их порядок, который сейчас играется. 
Для барда кнопка "Песня сыграна" напротив верхней в списке песни, для обновления списка с заказами

Список песен, которые можно заказать. 
Краткая информация о барде (ссылка на страницу барда)  , цель на что копит бард, 
Кнопка отметить песни которые хочешь заказать напротив песни. Они номеруются в какой очереди они будут в заказе клиента. 
Для барда + кнопка убрать песню из списков , которые можно заказать.

Кнопка оплатить заказ выделенных песен.    
Бургер меню со страницами сайте. Наполненность меню зависит от роли пользователя (не авторизованный/зарегестрированный авторизованный/ бард авторизованный)

Оставить комментарий. Оценить исполнение заказа спец символом. 


Страница барда со стороны пользователя. 

Подробная информация о барде. 
записи аудио и видео со своим творчеством, которые прикрепляет брад в настройках профиля
Расписание выступлений.
Геолокация нахождения барда.
Написать барду. Необходимоть авторизоваться 
Возможность заказать барда , если бард выставил такую возможность в настройках своего профиля. 
Комментарии оставленные с выступлений + оставить комментарий. 


Страница авторизации 

Блок авторизации, с кнопкой на регистрацию, -> блок регистрации (очень хотелось бы через гугл)


Страница кабинет авторизованного пользователя. 

"Мои сообщения" 
Подписка на бардов
Стать бардом
подстраница Настройка профиля (аватарка. ник, город, район (для больших городов)
подстраница Кошелек + история транзакций + привязать карту


Страница кабинет барда

"Мои сообщения"
Подписка на бардов
подстраница Настройка профиля (аватарка. ник, город, район (для больших городов)
Настройка страницы исполнителя (Страница барда со стороны пользователя.)

подстраница Кошелек + история транзакций + привязать карту
Настройка песен (песни которые можно заказать у меня)
Моя статистика (статистика прошедших выступлений и дохода)
Создать и запланировать  выступление(мероприятие) . Город, место. дата, время. Описание, картинки прикрепленные

Онлайн выступление - если запланированно онлайн(не живое выступление), То заходит . выступать, тут же чатик и возможность заказать песню . 


Поиск бардов. 

Изначально.  барды - список популярных бардов в городе пользователя. 
Фильтры: по оценкам, По нику, по геолокации. по инструменту, по жанру, по времени выступления, на улице или в помещении


Главная страница
Переход на нее из бургер меню, + из клика по логотипу сайта в верху страницы. 

"О нас", новости
